# Generated by Django 6.0 on 2026-01-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
