# Generated by Django 6.0 on 2026-01-02 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0002_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
